use serde::Serialize;

#[derive(Clone, Debug, Default, Serialize)]
pub struct Record {
    pub primary_ticket_no: String,
    pub ticket_no: String,
    pub coupon_no: String,
    pub issue_date: String,
    pub coupon_status: String,
    pub segment: String,
    pub flight_nr: String,
    pub dep_date_time: String,
    pub arr_date_time: String,
    pub cabin: String,
    pub rbd: String,
    pub pos: String,
    pub iata: String,
    pub distribution_channel: String,
    pub fare_basis: String,
    pub pnr_no: String,
    pub revenue: String,
    pub currency: String,
    pub tour_code: String,
    pub cpn_far_fare_amount_accounting_currency: String,
    pub net_fare_amount_accounting_currency: String,
    pub pub_fare_amount_accounting_currency: String,
    pub bal_exchange_additional_collected_fare_amount_accounting_currency: String,
    pub cpn_std_commission_amount_accounting_currency: String,
    pub std_commission_amount_accounting_currency: String,
    pub sup_commision_amount_accounting_currency: String,
    pub sum_cpn_txo_tax_amount_accounting_currency: String,
    pub cpn_txo_tax_amount_accounting_currency_yq: String,
    pub exchange_rate: String,
    pub document_status: String,
    pub trx_revenue_attributable_iata_number: String,
}
